language: node_js
node_js:
  - '12.22.1'
services: mongodb

before_install:
before_script:
  - cp client/.env.example client/.env
  - cp server/.env.example server/.env
  - npm run setup
  - npm run serve
