language: node_js
sudo: true
node_js:
  - '12.22.1'
addons:
  chrome: stable
services:
  - mongodb
  - xvfb
branches:
  only:
    - master
# before_install:
#   - apt update
#   - apt install wget
#   - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#   - dpkg -i google-chrome-stable_current_amd64.deb
before_script:
  - cp client/.env.example client/.env
  - cp server/.env.example server/.env
  - npm run setup
  - npm run serve &
  - until curl -s http://localhost:3000; do sleep 5; done
  - until curl -s http://localhost:5000; do sleep 5; done
script:
  - npm run testUI
